### ISSUE TITLE
Stable v1.0

### ISSUE THREAD

**Issue by f3l1x** [contributte/codeception#9]
To-do:
- change namespace to Contributte/Codeception
- change compose package to contributte/codeception
- abbandon arachne/codeception
- synchronize docs with contributte-style
- synchronize readme with contributte-style
- update Travis to use stages
- setup codesniffer

cc @enumag @mabar

**Comment by enumag** [comment]
Also drop the sensiolabs insight badge from readme + the .sensiolabs.yml file. They have changed their service in such a way it's no longer useful.

**Comment by enumag** [comment]
Btw. I have already updated the master branch to Nette 3.0 which was probably a mistake. It is impossible to make it compatible with both 2.4 and 3.0. We'll have to revert this.

**Comment by enumag** [comment]
Also if you want to use codesniffer it might be a good idea to use symplify/easy-coding-standard instead as it integrates both php-cs-fixer and codesniffer. I'm using it on my newest project and it's quite good.

**Comment by enumag** [comment]
@f3l1x Any update? To be honest I feel a bit bad about you transfering the repository instead of forking it, especially because nothing else happened after that. If I needed to fix a bug or add a new feature it would be a bit complicated now. Please don't do transfers for the other packages unless you want to finish the transition immediately after the transfer.

**Comment by f3l1x** [comment]
You right it´s my mistake. I will focus on it right now. Sorry for that. I will do my best.

**Comment by KacerCZ** [comment]
Hi, is there any reason why tag for version 1.0 does not exist?
